fernetKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
webserverSecretKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
executor: "KubernetesExecutor"

dags:
  gitSync:
    enabled: true
    repo: https://github.com/Nitin-Flavier13/KubernetesDataEng.git
    branch: master
    rev: HEAD 
    depth: 1 
    maxFailures: 0
    subPath: "dags"